fixing failing specs and adding additional submit inquiry positive case
teamlawfty/playwright-bdd-cucumber-2.0lawfty-prototype pull request #5
Opened 2024-10-03 15:55 UTC by MartinLichev

2024-10-03 18:29 UTC, elie-lawfty requested changes
One small change in the steps definition and a question.
Thank you.

2024-10-03 18:29 UTC, elie-lawfty commented on features/A1.Login/Sign-In.feature
> +    When I enter a valid "{env.EMAIL}" in the "email" field
Just a note on this, why do you have a step with `I enter a valid "{env.EMAIL}"` and another definition with `I enter a ìnvalid "invalid@mail.com"`?
Couldn't just be the same definition like the following?
`When I enter "{env.EMAIL}" in the "..." field`
I'm not sure adding the valid/invalid text makes sense here since you're actually specifying the value in the same line

2024-10-03 18:29 UTC, elie-lawfty commented on step-definitions/generic.steps.ts
> +                await element.waitFor({ state: 'visible', timeout: 25000 });
25s seems a little excessive here - why that much?

2024-10-04 10:00 UTC, MartinLichev commented on features/A1.Login/Sign-In.feature
> +    When I enter a valid "{env.EMAIL}" in the "email" field
hey Elie @elie-lawfty thanks for flagging this! Yes, you're right 
This has been fixed now with latest commit

2024-10-04 10:00 UTC, MartinLichev commented on step-definitions/generic.steps.ts
> +                await element.waitFor({ state: 'visible', timeout: 25000 });
This has been fixed as well

2024-10-11 15:48 UTC, merged